name: Package and Release

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v1
    - name: Zip manifest.json
      run: zip -1 -r release.xpi manifest.json
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.xpi"
